# docker-compose
version: '3'

services:
#        server:
#                build:
#                context: ./server
#                restart: always
#                ports:
#                - 3000:3000
#                networks:
#                - db-net
#                depends_on:
#                - db
        db:
                platform: linux/amd64
                image: mysql:latest
                container_name: mysql-test
                env_file: ./db/.env
#                networks:
#                - db-net
                ports:
                        - 3306:3306
                volumes:
                        - ./db/data:/var/lib/mysql
                

# networks:
#     db-net:
    
volumes:
        db:
